services:
  - type: web
    name: fb-offer-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --timeout 120
    plan: free
    envVars:
      - key: APP_ID
        sync: false
      - key: APP_SECRET
        sync: false
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: PAGE_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY2
        sync: false
      - key: GROQ_API_KEY3
        sync: false
      - key: GROQ_API_KEY4
        sync: false
      - key: GROQ_API_KEY5
        sync: false
